CREATE TABLE game_agent (
  id BIGINT(20) PRIMARY KEY AUTO_INCREMENT  NOT NULL,
  userid VARCHAR(100) NOT NULL,
  gameid VARCHAR(100) NOT NULL ,
  created timestamp DEFAULT CURRENT_TIMESTAMP,
  last_updated timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);