CREATE TABLE player_favorite (
  id BIGINT(20) PRIMARY KEY AUTO_INCREMENT  NOT NULL,
  playerid VARCHAR(100) NOT NULL UNIQUE,
  favorites VARCHAR(255) NOT NULL ,
  created timestamp DEFAULT CURRENT_TIMESTAMP,
  last_updated timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);