CREATE TABLE `promotion` (
  id BIGINT(20) PRIMARY KEY AUTO_INCREMENT  NOT NULL,
  `userid` BIGINT(20) NULL,
  `sort` INT(10) NULL,
  `created` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `last_updated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   UNIQUE KEY `unique_promotion` (`userid`),
    FOREIGN KEY (userid) REFERENCES user(id) ON UPDATE CASCADE ON DELETE RESTRICT);