CREATE TABLE keyword (
  id BIGINT(20) PRIMARY KEY AUTO_INCREMENT  NOT NULL,
  userid bigint,
  keywords VARCHAR(255) NOT NULL ,
  created timestamp DEFAULT CURRENT_TIMESTAMP,
  last_updated timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (userid) REFERENCES user(id) ON UPDATE CASCADE ON DELETE RESTRICT);
